#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.config/wallpapers/everforest-wave.png &
~/.config/polybar/launch.sh &
xrandr --output DP-2 --mode 1920x1080 --rate 144  &
picom --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	12 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false 

bspc config focus_follows_pointer true

bspc config normal_border_color "#272e33"
bspc config focused_border_color "#7fbbb3"

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

# how much of the screen the "master" takes by default
bspc config split_ratio 0.55
