#! /bin/sh

xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-scale ~/.config/wallpapers/everforest-wave.png &
~/.config/polybar/launch.sh &
xrandr --output DP-2 --mode 1920x1080 --rate 144  &
setxkbmap -option "caps:escape" &
dunst &
redshift -l 12.9:77.5 &
picom &

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

bspc config border_width         2
bspc config window_gap         	12 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false 

bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "#272e33"
bspc config focused_border_color "#7fbbb3"

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

# how much of the screen the "master" takes by default
bspc config split_ratio 0.55
